mfd: fusb302: Fix missing extcon functions declaration
Kernel 5.10 has different apis for using extcon properties and this
driver fails to compile because of that.

This commit fixes following errors:
../drivers/mfd/fusb302.c: In function 'platform_fusb_notify':
../drivers/mfd/fusb302.c:305:17: error: implicit declaration of function 'extcon_set_property'; did you mean 'extcon_get_property'? [-Werror=implicit-function-declaration]
  305 |                 extcon_set_property(chip->extcon, EXTCON_USB,
      |                 ^~~~~~~~~~~~~~~~~~~
      |                 extcon_get_property
../drivers/mfd/fusb302.c:319:17: error: implicit declaration of function 'extcon_set_state'; did you mean 'extcon_get_state'? [-Werror=implicit-function-declaration]
  319 |                 extcon_set_state(chip->extcon, EXTCON_USB, ufp);
      |                 ^~~~~~~~~~~~~~~~
      |                 extcon_get_state
../drivers/mfd/fusb302.c:322:17: error: implicit declaration of function 'extcon_sync' [-Werror=implicit-function-declaration]
  322 |                 extcon_sync(chip->extcon, EXTCON_USB);
      |                 ^~~~~~~~~~~
  CC      drivers/gpu/drm/rockchip/cdn-dp-core.o
  CC      drivers/gpu/drm/rockchip/cdn-dp-reg.o
../drivers/mfd/fusb302.c: In function 'fusb30x_probe':
../drivers/mfd/fusb302.c:3464:24: error: implicit declaration of function 'devm_extcon_dev_allocate' [-Werror=implicit-function-declaration]
 3464 |         chip->extcon = devm_extcon_dev_allocate(&client->dev, fusb302_cable);
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~
../drivers/mfd/fusb302.c:3464:22: warning: assignment to 'struct extcon_dev *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
error, forbidden warning:fusb302.c:3464
 3464 |         chip->extcon = devm_extcon_dev_allocate(&client->dev, fusb302_cable);
      |                      ^
../drivers/mfd/fusb302.c:3470:15: error: implicit declaration of function 'devm_extcon_dev_register'; did you mean 'devm_led_classdev_register'? [-Werror=implicit-function-declaration]
 3470 |         ret = devm_extcon_dev_register(&client->dev, chip->extcon);
      |               ^~~~~~~~~~~~~~~~~~~~~~~~
      |               devm_led_classdev_register
../drivers/mfd/fusb302.c:3477:15: error: implicit declaration of function 'extcon_set_property_capability'; did you mean 'extcon_get_property_capability'? [-Werror=implicit-function-declaration]
 3477 |         ret = extcon_set_property_capability(chip->extcon, EXTCON_USB,
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |               extcon_get_property_capability

Change-Id: I0c2ef8160bc60acc1977171aa07c942f734a7efc
Signed-off-by: UtsavBalar1231 <utsavbalar1231@gmail.com>