gpu: mali400: Fix strict-protypes warning in mali_executor_is_working()
Clang 15 complains about its newly introduced strict protypes analysis
and a function declared without a protype is now illegal to use.

This fixes the clang 15 introduced error:
../drivers/gpu/arm/mali400/mali/common/mali_executor.c:1386:42: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
static mali_bool mali_executor_is_working()
                                         ^
                                          void
1 error generated.

Change-Id: I168d53571724125b73a75a69e7e5e60b38a60a70
Signed-off-by: UtsavBalar1231 <utsavbalar1231@gmail.com>